name: Sync Branches

on:
  schedule:
    # 每天10点UTC（你可以根据需要调整时区）
    - cron: '0 10 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Add remote for MoreTore/openpilot
        run: |
          git remote add moretore https://github.com/MoreTore/openpilot.git
          git fetch moretore mazda-frogpilot-dev

      - name: Add remote for FrogAi/FrogPilot
        run: |
          git remote add frogai https://github.com/FrogAi/FrogPilot.git
          git fetch frogai

      - name: Merge `mazda-frogpilot-dev` into current branch
        run: |
          git checkout main  # 你可以修改为目标分支
          git merge moretore/mazda-frogpilot-dev --no-ff --commit -m "Sync with mazda-frogpilot-dev"

      - name: Merge `FrogPilot` into current branch
        run: |
          git merge frogai/FrogPilot --no-ff --commit -m "Sync with FrogPilot"

      - name: Push changes back to the main repository
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
