name: Sync on Upstream Update

on:
    types: [upstream-updated]
  workflow_dispatch:

jobs:
  sync_and_modify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: cncp

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/jixiexiaoge/openpilot.git

      - name: Reset to Upstream
        run: |
          git fetch upstream cncp
          git reset --hard upstream/cncp

      - name: Modify values.py with sed
        run: |
          # Code to add
          CODE_TO_ADD="
          if __name__ == \"__main__\":
            cars = []
            for platform in CAR:
              for doc in platform.config.car_docs:
                cars.append(doc.name)
            cars.sort()
            for c in cars:
              print(c)
          "

          # 使用 sed 命令将代码添加到 values.py 文件的末尾，如果代码不存在
          if ! grep -q "$CODE_TO_ADD" openpilot/opendbc_repo/opendbc/car/toyota/values.py; then
            echo "$CODE_TO_ADD" >> openpilot/opendbc_repo/opendbc/car/toyota/values.py
          else
            echo "Code already exists in values.py, skipping modification."
          fi

      - name: Commit and Push Changes
        run: |
          git add opendbc_repo/opendbc/car/toyota/values.py
          git commit -m "Sync with jixiexiaoge/openpilot cncp (reset to upstream) and modify values.py"
          git push origin cncp -f
